# .github/workflows/documentation.yml
name: Documentation

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "./Sources"
          module-name: SwiftGame
          output: "./Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "./Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.swift_doc_access_token }}
